name: grocery
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


 
    

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  intl: ^0.17.0
  rflutter_alert: ^2.0.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  badges: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


    

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  fonts:
    - family: Adobe Devanagari
      fonts:
        - asset: assets/fonts/adobe-devanagari.otf
          weight: 500
        - asset: assets/fonts/adobe-devanagari_844.otf
    - family: TCM
      fonts:
        - asset: assets/fonts/TCM.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoSlab.ttf    