name: grocery
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


 
    

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  intl: ^0.17.0
  rflutter_alert: ^2.0.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  badges: ^2.0.1
  pull_to_refresh: ^2.0.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.2
  shared_preferences: ^2.0.7
  provider: ^6.0.0
  flutter_slidable: ^0.6.0
  firebase_messaging: ^10.0.7
  flutter_local_notifications: 5.0.0+1
  http: ^0.13.0
  permission_handler: ^6.0.0
  flutter_phone_direct_caller: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


    

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  fonts:
    - family: Adobe Devanagari
      fonts:
        - asset: assets/fonts/adobe-devanagari.otf
          weight: 500
        - asset: assets/fonts/adobe-devanagari_844.otf
    - family: TCM
      fonts:
        - asset: assets/fonts/TCM.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoSlab.ttf    